version: "3"
services:
  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "9000:9000"
      - "9001:80"
    volumes:
      - ./src:/var/www/html
    networks:
      connected:
  mongo:
    image: mongo

    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=p@sw0rd
    ports:
      - "9003:27017"
    networks:
      connected:
networks:
  connected: